# Generated by Django 4.2.16 on 2025-04-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('default', 'Стандартная задача'), ('benchmark', 'Бенчмарк'), ('batch', 'Пакетная обработка')], default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='worker_tags',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
