# Generated by Django 4.2.16 on 2025-04-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_task_task_type_task_worker_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_type',
        ),
        migrations.RemoveField(
            model_name='task',
            name='worker_tags',
        ),
        migrations.AddField(
            model_name='task',
            name='worker_type',
            field=models.CharField(choices=[('default', 'Стандартный воркер'), ('gpu', 'Более быстрый воркер'), ('highmem', 'Стандартный воркер с бОльшим объёмом памяти')], default='default', max_length=100),
        ),
    ]
