# Generated by Django 4.2.21 on 2025-05-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_benchmark_worker_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='_worker_types',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
