# Generated by Django 4.2.21 on 2025-05-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_remove_task_worker_type_benchmark_worker_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='worker_type',
            field=models.CharField(choices=[('default', 'Стандартный воркер'), ('gpu', 'Более быстрый воркер'), ('highmem', 'Стандартный воркер с бОльшим объёмом памяти')], default='default', max_length=100),
        ),
    ]
