# Generated by Django 4.2.21 on 2025-05-12 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_task_worker_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='worker_type',
        ),
    ]
